spring.application.name=ghosted

# Profile switching logic
# Default to dev if SPRING_PROFILES_ACTIVE is not set
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Use the environment variable PORT provided by Render
server.port=${PORT:8080}
